sudo: required
services:
  -docker


before_install:
  - docker build -t jimmyleu/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jimmyleu/react-test npm test -- --coverage


after_success:
  - docker build -t jimmyleu/multi-client ./client
  - docker build -t jimmyleu/multi-nginx ./nginx
  - docker build -t jimmyleu/multi-server ./server
  - docker build -t jimmyleu/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push jimmyleu/multi-client
  - docker push jimmyleu/multi-nginx
  - docker push jimmyleu/multi-server
  - docker push jimmyleu/multi-worker
